# Database
spring:
  datasource:
    url: ${DB_URL}
    username: ${PG_USER}
    password: ${PG_PASSWORD}
  jpa:
    format_sql: true
    hibernate:
      ddl-auto: create-drop
      properties:
        hibernate.format_sql: true

springdoc:
  swagger-ui:
      path: /swagger-ui.html


  api-docs:
    path: /api-docs